"""
Add the two partial UniqueConstraints on CompetencyCriteriaGroup that #665 relies on.

create_leaf_group() uses them for race-safe root/course-level group creation: a
get_or_create() that loses the race falls back to fetching the row its competitor just
committed, instead of the two ending up with duplicate roots or course-level groups.
"""
# Generated by Django 5.2.16 on 2026-09-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_learning', '0006_competencycriterion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competencycriteriagroup',
            constraint=models.UniqueConstraint(
                fields=('tag',),
                condition=models.Q(('parent__isnull', True)),
                name='oel_cbe_criteria_group_one_root_per_tag',
                violation_error_message='A competency tag may have at most one root CompetencyCriteriaGroup.',
            ),
        ),
        migrations.AddConstraint(
            model_name='competencycriteriagroup',
            constraint=models.UniqueConstraint(
                fields=('tag', 'course', 'parent'),
                condition=models.Q(('course__isnull', False)),
                name='oel_cbe_criteria_group_one_course_group_per_tag_course',
                violation_error_message=(
                    'A competency tag may have at most one course-level CompetencyCriteriaGroup per course.'
                ),
            ),
        ),
    ]
